name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
          - goos: windows
            goarch: amd64
          - goos: freebsd
            goarch: amd64
          - goos: freebsd
            goarch: arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Build
        run: |
          mkdir -p dist
          export CGO_ENABLED=0
          export GOOS=${{ matrix.goos }}
          export GOARCH=${{ matrix.goarch }}

          APP_NAME=$(basename $GITHUB_REPOSITORY)

          EXT=""
          if [ "$GOOS" = "windows" ]; then
            EXT=".exe"
          fi

          OUTPUT=${APP_NAME}-${GOOS}-${GOARCH}${EXT}

          go build -ldflags "-s -w" -o $OUTPUT .

          ZIP_NAME=dist/${APP_NAME}-${GOOS}-${GOARCH}.zip

          zip $ZIP_NAME $OUTPUT

          if ls *.html >/dev/null 2>&1; then
            zip -j $ZIP_NAME *.html
          fi

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/*.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Prepare files
        run: |
          mkdir upload
          find dist -name "*.zip" -exec cp {} upload/ \;

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: upload/*.zip
